// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Hcp
{
    public static class GetConsulAgentKubernetesSecret
    {
        /// <summary>
        /// The agent config Kubernetes secret data source provides Consul agents running in Kubernetes the configuration needed to connect to the Consul cluster.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Hcp = Pulumi.Hcp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var test = Hcp.GetConsulAgentKubernetesSecret.Invoke(new()
        ///     {
        ///         ClusterId = @var.Cluster_id,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetConsulAgentKubernetesSecretResult> InvokeAsync(GetConsulAgentKubernetesSecretArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetConsulAgentKubernetesSecretResult>("hcp:index/getConsulAgentKubernetesSecret:getConsulAgentKubernetesSecret", args ?? new GetConsulAgentKubernetesSecretArgs(), options.WithDefaults());

        /// <summary>
        /// The agent config Kubernetes secret data source provides Consul agents running in Kubernetes the configuration needed to connect to the Consul cluster.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Hcp = Pulumi.Hcp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var test = Hcp.GetConsulAgentKubernetesSecret.Invoke(new()
        ///     {
        ///         ClusterId = @var.Cluster_id,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetConsulAgentKubernetesSecretResult> Invoke(GetConsulAgentKubernetesSecretInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetConsulAgentKubernetesSecretResult>("hcp:index/getConsulAgentKubernetesSecret:getConsulAgentKubernetesSecret", args ?? new GetConsulAgentKubernetesSecretInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetConsulAgentKubernetesSecretArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the HCP Consul cluster.
        /// </summary>
        [Input("clusterId", required: true)]
        public string ClusterId { get; set; } = null!;

        public GetConsulAgentKubernetesSecretArgs()
        {
        }
        public static new GetConsulAgentKubernetesSecretArgs Empty => new GetConsulAgentKubernetesSecretArgs();
    }

    public sealed class GetConsulAgentKubernetesSecretInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the HCP Consul cluster.
        /// </summary>
        [Input("clusterId", required: true)]
        public Input<string> ClusterId { get; set; } = null!;

        public GetConsulAgentKubernetesSecretInvokeArgs()
        {
        }
        public static new GetConsulAgentKubernetesSecretInvokeArgs Empty => new GetConsulAgentKubernetesSecretInvokeArgs();
    }


    [OutputType]
    public sealed class GetConsulAgentKubernetesSecretResult
    {
        /// <summary>
        /// The ID of the HCP Consul cluster.
        /// </summary>
        public readonly string ClusterId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The Consul agent configuration in the format of a Kubernetes secret (YAML).
        /// </summary>
        public readonly string Secret;

        [OutputConstructor]
        private GetConsulAgentKubernetesSecretResult(
            string clusterId,

            string id,

            string secret)
        {
            ClusterId = clusterId;
            Id = id;
            Secret = secret;
        }
    }
}
