// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcp

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The Consul versions data source provides the Consul versions supported by HCP.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-hcp/sdk/go/hcp"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := hcp.GetConsulVersions(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetConsulVersions(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetConsulVersionsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetConsulVersionsResult
	err := ctx.Invoke("hcp:index/getConsulVersions:getConsulVersions", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getConsulVersions.
type GetConsulVersionsResult struct {
	// The Consul versions available on HCP.
	Availables []string `pulumi:"availables"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The preview versions of Consul available on HCP.
	Previews []string `pulumi:"previews"`
	// The recommended Consul version for HCP clusters.
	Recommended string `pulumi:"recommended"`
}
