// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package hcp

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The HVN route data source provides information about an existing HVN route.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-hcp/sdk/go/hcp"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := hcp.LookupHvnRoute(ctx, &GetHvnRouteArgs{
// 			HvnLink:         _var.Hvn_link,
// 			DestinationCidr: _var.Hvn_route_id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupHvnRoute(ctx *pulumi.Context, args *LookupHvnRouteArgs, opts ...pulumi.InvokeOption) (*LookupHvnRouteResult, error) {
	var rv LookupHvnRouteResult
	err := ctx.Invoke("hcp:index/getHvnRoute:getHvnRoute", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getHvnRoute.
type LookupHvnRouteArgs struct {
	// The `selfLink` of the HashiCorp Virtual Network (HVN).
	HvnLink string `pulumi:"hvnLink"`
	// The ID of the HVN route.
	HvnRouteId string `pulumi:"hvnRouteId"`
}

// A collection of values returned by getHvnRoute.
type LookupHvnRouteResult struct {
	// The time that the HVN route was created.
	CreatedAt string `pulumi:"createdAt"`
	// The destination CIDR of the HVN route.
	DestinationCidr string `pulumi:"destinationCidr"`
	// The `selfLink` of the HashiCorp Virtual Network (HVN).
	HvnLink string `pulumi:"hvnLink"`
	// The ID of the HVN route.
	HvnRouteId string `pulumi:"hvnRouteId"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// A unique URL identifying the HVN route.
	SelfLink string `pulumi:"selfLink"`
	// The state of the HVN route.
	State string `pulumi:"state"`
	// A unique URL identifying the target of the HVN route.
	TargetLink string `pulumi:"targetLink"`
}

func LookupHvnRouteOutput(ctx *pulumi.Context, args LookupHvnRouteOutputArgs, opts ...pulumi.InvokeOption) LookupHvnRouteResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupHvnRouteResult, error) {
			args := v.(LookupHvnRouteArgs)
			r, err := LookupHvnRoute(ctx, &args, opts...)
			return *r, err
		}).(LookupHvnRouteResultOutput)
}

// A collection of arguments for invoking getHvnRoute.
type LookupHvnRouteOutputArgs struct {
	// The `selfLink` of the HashiCorp Virtual Network (HVN).
	HvnLink pulumi.StringInput `pulumi:"hvnLink"`
	// The ID of the HVN route.
	HvnRouteId pulumi.StringInput `pulumi:"hvnRouteId"`
}

func (LookupHvnRouteOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHvnRouteArgs)(nil)).Elem()
}

// A collection of values returned by getHvnRoute.
type LookupHvnRouteResultOutput struct{ *pulumi.OutputState }

func (LookupHvnRouteResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupHvnRouteResult)(nil)).Elem()
}

func (o LookupHvnRouteResultOutput) ToLookupHvnRouteResultOutput() LookupHvnRouteResultOutput {
	return o
}

func (o LookupHvnRouteResultOutput) ToLookupHvnRouteResultOutputWithContext(ctx context.Context) LookupHvnRouteResultOutput {
	return o
}

// The time that the HVN route was created.
func (o LookupHvnRouteResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The destination CIDR of the HVN route.
func (o LookupHvnRouteResultOutput) DestinationCidr() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.DestinationCidr }).(pulumi.StringOutput)
}

// The `selfLink` of the HashiCorp Virtual Network (HVN).
func (o LookupHvnRouteResultOutput) HvnLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.HvnLink }).(pulumi.StringOutput)
}

// The ID of the HVN route.
func (o LookupHvnRouteResultOutput) HvnRouteId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.HvnRouteId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupHvnRouteResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.Id }).(pulumi.StringOutput)
}

// A unique URL identifying the HVN route.
func (o LookupHvnRouteResultOutput) SelfLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.SelfLink }).(pulumi.StringOutput)
}

// The state of the HVN route.
func (o LookupHvnRouteResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.State }).(pulumi.StringOutput)
}

// A unique URL identifying the target of the HVN route.
func (o LookupHvnRouteResultOutput) TargetLink() pulumi.StringOutput {
	return o.ApplyT(func(v LookupHvnRouteResult) string { return v.TargetLink }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupHvnRouteResultOutput{})
}
