// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package hcp

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The Packer Image data source iteration gets the most recent iteration (or build) of an image, given a channel.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/grapl-security/pulumi-hcp/sdk/go/hcp"
// 	"github.com/pulumi/pulumi-hcp/sdk/go/hcp"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := hcp.GetPackerIteration(ctx, &GetPackerIterationArgs{
// 			BucketName: "hardened-ubuntu-16-04",
// 			Channel:    "megan-test",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func GetPackerIteration(ctx *pulumi.Context, args *GetPackerIterationArgs, opts ...pulumi.InvokeOption) (*GetPackerIterationResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetPackerIterationResult
	err := ctx.Invoke("hcp:index/getPackerIteration:getPackerIteration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPackerIteration.
type GetPackerIterationArgs struct {
	BucketName string `pulumi:"bucketName"`
	Channel    string `pulumi:"channel"`
}

// A collection of values returned by getPackerIteration.
type GetPackerIterationResult struct {
	AuthorId    string `pulumi:"authorId"`
	BucketName  string `pulumi:"bucketName"`
	Channel     string `pulumi:"channel"`
	CreatedAt   string `pulumi:"createdAt"`
	Fingerprint string `pulumi:"fingerprint"`
	// The provider-assigned unique ID for this managed resource.
	Id                 string `pulumi:"id"`
	IncrementalVersion int    `pulumi:"incrementalVersion"`
	OrganizationId     string `pulumi:"organizationId"`
	ProjectId          string `pulumi:"projectId"`
	Ulid               string `pulumi:"ulid"`
	UpdatedAt          string `pulumi:"updatedAt"`
}

func GetPackerIterationOutput(ctx *pulumi.Context, args GetPackerIterationOutputArgs, opts ...pulumi.InvokeOption) GetPackerIterationResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPackerIterationResult, error) {
			args := v.(GetPackerIterationArgs)
			r, err := GetPackerIteration(ctx, &args, opts...)
			var s GetPackerIterationResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetPackerIterationResultOutput)
}

// A collection of arguments for invoking getPackerIteration.
type GetPackerIterationOutputArgs struct {
	BucketName pulumi.StringInput `pulumi:"bucketName"`
	Channel    pulumi.StringInput `pulumi:"channel"`
}

func (GetPackerIterationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPackerIterationArgs)(nil)).Elem()
}

// A collection of values returned by getPackerIteration.
type GetPackerIterationResultOutput struct{ *pulumi.OutputState }

func (GetPackerIterationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPackerIterationResult)(nil)).Elem()
}

func (o GetPackerIterationResultOutput) ToGetPackerIterationResultOutput() GetPackerIterationResultOutput {
	return o
}

func (o GetPackerIterationResultOutput) ToGetPackerIterationResultOutputWithContext(ctx context.Context) GetPackerIterationResultOutput {
	return o
}

func (o GetPackerIterationResultOutput) AuthorId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.AuthorId }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) BucketName() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.BucketName }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) Channel() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.Channel }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.Fingerprint }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetPackerIterationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) IncrementalVersion() pulumi.IntOutput {
	return o.ApplyT(func(v GetPackerIterationResult) int { return v.IncrementalVersion }).(pulumi.IntOutput)
}

func (o GetPackerIterationResultOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.OrganizationId }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) Ulid() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.Ulid }).(pulumi.StringOutput)
}

func (o GetPackerIterationResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v GetPackerIterationResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPackerIterationResultOutput{})
}
