// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Hcp.Inputs
{

    public sealed class VaultClusterMetricsConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Datadog api key for streaming metrics
        /// </summary>
        [Input("datadogApiKey")]
        public Input<string>? DatadogApiKey { get; set; }

        /// <summary>
        /// Datadog region for streaming metrics
        /// </summary>
        [Input("datadogRegion")]
        public Input<string>? DatadogRegion { get; set; }

        /// <summary>
        /// Grafana endpoint for streaming metrics
        /// </summary>
        [Input("grafanaEndpoint")]
        public Input<string>? GrafanaEndpoint { get; set; }

        /// <summary>
        /// Grafana password for streaming metrics
        /// </summary>
        [Input("grafanaPassword")]
        public Input<string>? GrafanaPassword { get; set; }

        /// <summary>
        /// Grafana user for streaming metrics
        /// </summary>
        [Input("grafanaUser")]
        public Input<string>? GrafanaUser { get; set; }

        /// <summary>
        /// Splunk endpoint for streaming metrics
        /// </summary>
        [Input("splunkHecendpoint")]
        public Input<string>? SplunkHecendpoint { get; set; }

        /// <summary>
        /// Splunk token for streaming metrics
        /// </summary>
        [Input("splunkToken")]
        public Input<string>? SplunkToken { get; set; }

        public VaultClusterMetricsConfigArgs()
        {
        }
        public static new VaultClusterMetricsConfigArgs Empty => new VaultClusterMetricsConfigArgs();
    }
}
