// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The AWS network peering data source provides information about an existing network peering between an HVN and a peer AWS VPC.
 */
export function getAwsNetworkPeering(args: GetAwsNetworkPeeringArgs, opts?: pulumi.InvokeOptions): Promise<GetAwsNetworkPeeringResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("hcp:index/getAwsNetworkPeering:getAwsNetworkPeering", {
        "hvnId": args.hvnId,
        "peeringId": args.peeringId,
        "waitForActiveState": args.waitForActiveState,
    }, opts);
}

/**
 * A collection of arguments for invoking getAwsNetworkPeering.
 */
export interface GetAwsNetworkPeeringArgs {
    hvnId: string;
    peeringId: string;
    waitForActiveState?: boolean;
}

/**
 * A collection of values returned by getAwsNetworkPeering.
 */
export interface GetAwsNetworkPeeringResult {
    readonly createdAt: string;
    readonly expiresAt: string;
    readonly hvnId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly organizationId: string;
    readonly peerAccountId: string;
    readonly peerVpcId: string;
    readonly peerVpcRegion: string;
    readonly peeringId: string;
    readonly projectId: string;
    readonly providerPeeringId: string;
    readonly selfLink: string;
    readonly state: string;
    readonly waitForActiveState?: boolean;
}

export function getAwsNetworkPeeringOutput(args: GetAwsNetworkPeeringOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAwsNetworkPeeringResult> {
    return pulumi.output(args).apply(a => getAwsNetworkPeering(a, opts))
}

/**
 * A collection of arguments for invoking getAwsNetworkPeering.
 */
export interface GetAwsNetworkPeeringOutputArgs {
    hvnId: pulumi.Input<string>;
    peeringId: pulumi.Input<string>;
    waitForActiveState?: pulumi.Input<boolean>;
}
